FROM node:25-slim

WORKDIR /app

COPY package*.json ./

RUN npm install --omit=dev && npm cache clean --force

COPY . .

# Получаем переменную из docker-compose
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL

RUN npm install -g serve
# Собираем production build
RUN npm run build

# Запускаем HTTP сервер для раздачи статики
CMD ["serve", "-s", "build", "-l", "3000"]

EXPOSE 3000
